apiVersion: v1
kind: Service
metadata:
  name: microblogservice
  labels:
    app: microblog
spec:
  selector:
    app: microblog
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 5000
      nodePort: 30000